minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: flow-manager

scheduler:
  fixed-rate: 3s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

outbox:
  check-lock:
    max-attempts: 300
    timeout: PT1M

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flow
    username: POSTGRES
    password: 12345

  application:
    name: flow-manager

  kafka:
    topics:
      file-update: file-update-topic
      file-failed: file-failed-topic
      file-update-dlt: file-update-dlt-topic

    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: Flow-manager
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  jpa:
    hibernate:
      ddl-auto: none