minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: flow-manager
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flow
    username: POSTGRES
    password: 12345

  kafka:
    topics:
      file-update: file-update-topic
      file-upload: file-upload-topic
      file-failed: file-failed-topic
      file-dlt: file-update-dlt-topic
      file-completed: file-completed-topic


    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: Flow-manager
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  jpa:
    hibernate:
      ddl-auto: create-drop